### ISSUE TITLE
Links to Battlelog profiles are broken

### ISSUE THREAD

**Issue by robled** [DontCamp/bf4-server-status#17]
Valid link:  http://battlelog.battlefield.com/bf4/soldier/DC-DontComplain/stats/196697680/pc/

Link generated by bf4-server-status:  http://battlelog.battlefield.com/bf4/soldier/DC-DontComplain/stats//pc/

Seems that personaId is no longer being provided by the BF4DB API:

http://api.bf4db.com/api-player.php?format=json&name=DC-DontComplain

**Comment by seandst** [comment]
I guess they're trying to drive traffic to bf4db first, and we should use `bf4db_url`?

**Comment by robled** [comment]
Sounds good.  It's a bit more convenient to have the Battlelog profiles available directly, but meh.

**Comment by robled** [comment]
quick fix = replace battlelog links with bf4db.com links.  You can still get to the battlelog profiles from the bf4db.com page.
